- name: Ensure MariaDB is installed
  ansible.builtin.apt:
    name: mariadb-server
    state: present
  become: true

- name: Ensure MariaDB is started and enabled
  ansible.builtin.service:
    name: mariadb 
    state: started
    enabled: true
  become: true

- name:  Set MariaDB root password 
  command: mysqladmin -u root password "{{ db_root_password }}"
  ignore_errors: yes 